name: golangci

on:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci.yml'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code int the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: "--config=.golangci.yml ./..."
          only-new-issues: false
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
          install-mode: binary
